name: farm_direct
description: A application to connect farmers to consumers

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0
  flutter_native_splash: ^1.1.0
  url_launcher: ^5.7.10
  shimmer: ^1.1.2
  cached_network_image: ^2.5.1
  flutter_feather_icons: ^1.0.3
  like_button: ^2.0.1
  flutter_rating_bar: ^4.0.0
  responsive_flutter: ^0.0.4
  carousel_pro: ^1.0.0
  smooth_page_indicator: ^0.2.3
  image_picker: ^0.7.4
  flutter_staggered_grid_view: ^0.3.4
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  path_provider: ^2.0.1
  http: ^0.13.1
  provider: ^5.0.0
  google_maps_flutter: ^2.0.3
  geocoding:
  geolocator:
  shared_preferences: ^2.0.5
  page_transition: ^1.1.7+6
  razorpay_flutter: ^1.2.6
  fluttertoast: ^8.0.6
  dio: ^4.0.0
  badges: ^1.2.0
  flutter_markdown: ^0.6.1
  modal_bottom_sheet: ^2.0.0
  country_list_pick: ^1.0.1+4
  video_player: ^2.1.3
  timeago: ^3.0.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  build_runner: ^1.12.2
  flutter_launcher_icons: ^0.9.1

flutter_icons:
  image_path: "assets/images/main_logo/main_logo.png"
  android: true
  ios: true
  

# run: flutter clean && flutter pub get && flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#000000"
#  image: assets/images/splash_screen/Splash.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/
    - assets/images/intro_slider_screen/
    - assets/images/main_logo/main_logo.png
    - assets/images/nav_bar_logo/
    - assets/images/
    - assets/images/deals_images/
    - assets/images/splash_screen/
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Medium.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
